# Generated by Django 5.0 on 2023-12-20 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupon_management', '0002_alter_allowedusersrule_options_and_more'),
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dicount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='اخرین بروزرسانی')),
                ('passenger_type', models.CharField(choices=[('adult', 'بزرگسال'), ('child', 'کودک'), ('baby', 'نوزاد')], max_length=10, verbose_name='نوع مسافر')),
                ('passenegr_number', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد مسافران')),
                ('basic_price', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='قیمت پایه')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon_management.couponuser')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='flight.flight')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
                'db_table': 'price',
            },
        ),
    ]
