# Generated by Django 5.0 on 2023-12-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_alter_price_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='تخفیف لحظه ای'),
        ),
    ]
