# Generated by Django 5.0 on 2023-12-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_price_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='بخ صورت لحظه ای ادمین میتواند تخفیف رو اعمل کند', max_digits=15, null=True, verbose_name='تخفیف لحظه ای'),
        ),
    ]
