# Generated by Django 5.0 on 2023-12-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0004_alter_price_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='precent_value_added_tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='به صورت درصدی میتوان وارد کرد', max_digits=5, null=True, verbose_name='مالیات بر ارزش افزوده'),
        ),
    ]
