# Generated by Django 5.0 on 2023-12-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0005_price_precent_value_added_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='precent_taxes_and_services',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='به صورت درصدی میتوان وارد کرد', max_digits=5, null=True, verbose_name='مالیات و خدمات'),
        ),
    ]
