# Generated by Django 5.0 on 2023-12-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0006_price_precent_taxes_and_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='cansellation_penalty_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='به صورت درصدی میتوان ان را وارد کرد', max_digits=5, null=True, verbose_name='جریمه کنسلی'),
        ),
        migrations.AlterField(
            model_name='price',
            name='precent_taxes_and_services',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='به صورت درصدی می توان ان را وارد کرد', max_digits=5, null=True, verbose_name='مالیات و خدمات'),
        ),
    ]
