# Generated by Django 5.0 on 2023-12-19 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.CharField(max_length=64, verbose_name='نام شرکت هواپیما')),
                ('airline_image', models.ImageField(blank=True, null=True, upload_to='airline/%Y/%M/%d', verbose_name='عکس')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('airport_type', models.CharField(max_length=50, verbose_name='نوع هواپیما')),
                ('allowed_cargo', models.PositiveSmallIntegerField(verbose_name='بار مجاز')),
                ('airport_cabin', models.CharField(max_length=50, verbose_name='کابین')),
                ('airport_class', models.CharField(max_length=50, verbose_name='کلاس نرخی')),
                ('airport_number_of_seates', models.PositiveIntegerField(verbose_name='تعداد صندلی های هواپمیا')),
                ('startus_airline', models.BooleanField(default=True, verbose_name='وضعیت شرکت هواپیمایی')),
                ('class_cabin_choose', models.CharField(choices=[('Economy', 'کلاس اقتصادی'), ('Business', 'کلاس کسب و کار'), ('First', 'کلاس اول')], default='Economy', max_length=8, verbose_name='کلاس هواپیما')),
                ('airline_rate_choose', models.CharField(choices=[('scpecial', 'نرخ ويژه'), ('normal', 'نرخ عادی')], default='normal', max_length=8, verbose_name='نوع نرخ هواپیما')),
            ],
            options={
                'verbose_name': 'AirLine',
                'verbose_name_plural': 'AirLines',
                'db_table': 'airline',
            },
        ),
        migrations.CreateModel(
            name='FlightAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=50, verbose_name='ويژگی')),
            ],
            options={
                'verbose_name': 'airline attribute',
                'verbose_name_plural': 'airline attributes',
                'db_table': 'airline attribute',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=50, verbose_name='مبدا')),
                ('destination', models.CharField(max_length=50, verbose_name='مقصد')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('flight_start_time', models.DateTimeField(verbose_name='ساعت پرواز')),
                ('flight_end_time', models.DateTimeField(verbose_name='ساعت فرود')),
                ('status_flight', models.BooleanField(verbose_name='وضعیت پرواز')),
                ('aairline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='flight.airline', verbose_name='پرواز')),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
                'db_table': 'flight',
            },
        ),
        migrations.CreateModel(
            name='FlightAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atribute_value', models.CharField(max_length=100, verbose_name='مقدار ويژگی')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='flight.flightattribute')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_attribute_values', to='flight.flight')),
            ],
            options={
                'verbose_name': 'FlightAttributeValue',
                'verbose_name_plural': 'FlightAttributeValues',
                'db_table': 'flight_attribute_value',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_type', models.CharField(choices=[('adult', 'بزرگسال'), ('child', 'کودک'), ('baby', 'نوزاد')], max_length=10, verbose_name='نوع مسافر')),
                ('passenegr_number', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد مسافران')),
                ('basic_price', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='قیمت پایه')),
                ('taxes_and_duties', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='مالیات و عوارض')),
                ('taxes_and_services', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='مالیات و خدمات')),
                ('value_added_tax', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='مالیات بر ارزش افزوده')),
                ('discount', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='تخفیف')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='flight.flight')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
                'db_table': 'price',
            },
        ),
    ]
