# Generated by Django 5.0 on 2023-12-20 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='اخرین بروزرسانی')),
                ('airline_name', models.CharField(max_length=64, verbose_name='نام شرکت هواپیما')),
                ('airline_image', models.ImageField(blank=True, null=True, upload_to='airline/%Y/%M/%d', verbose_name='عکس')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('airport_type', models.CharField(max_length=50, verbose_name='نوع هواپیما')),
                ('allowed_cargo', models.PositiveSmallIntegerField(verbose_name='بار مجاز')),
                ('airport_cabin', models.CharField(max_length=50, verbose_name='نوع کابین')),
                ('airport_class', models.CharField(max_length=50, verbose_name='کلاس نرخی')),
                ('airport_number_of_seates', models.PositiveIntegerField(verbose_name='تعداد صندلی های هواپمیا')),
                ('startus_airline', models.BooleanField(default=True, verbose_name='وضعیت شرکت هواپیمایی')),
                ('class_cabin_choose', models.CharField(choices=[('Economy', 'کلاس اقتصادی'), ('Premier Economy ', 'کلاس اقتصادی پریمیوم'), ('Business', 'کلاس کسب و کار'), ('Business_Premuir', 'کلاس بیزینس پریمیر'), ('First', 'کلاس فرست'), ('First_Premier', 'کلاس فرست پریمیر')], default='Economy', max_length=16, verbose_name='کلاس هواپیما')),
                ('airline_rate_choose', models.CharField(choices=[('scpecial', 'نرخ ويژه'), ('normal', 'نرخ عادی')], default='normal', max_length=8, verbose_name='نوع نرخ هواپیما')),
            ],
            options={
                'verbose_name': 'AirLine',
                'verbose_name_plural': 'AirLines',
                'db_table': 'airline',
            },
        ),
        migrations.CreateModel(
            name='FlightAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='اخرین بروزرسانی')),
                ('attribute', models.CharField(max_length=50, verbose_name='ويژگی')),
            ],
            options={
                'verbose_name': 'airline attribute',
                'verbose_name_plural': 'airline attributes',
                'db_table': 'airline attribute',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='اخرین بروزرسانی')),
                ('flght_path_choose', models.CharField(choices=[('wan way', 'یک طرفه'), ('back and forth', 'رفت و برگشت')], max_length=14, verbose_name=' مسیر پرواز')),
                ('origin', models.CharField(max_length=50, verbose_name='مبدا')),
                ('destination', models.CharField(max_length=50, verbose_name='مقصد')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('flight_start_time', models.DateTimeField(verbose_name='ساعت پرواز')),
                ('flight_end_time', models.DateTimeField(verbose_name='ساعت فرود')),
                ('status_flight', models.BooleanField(verbose_name='وضعیت پرواز')),
                ('aairline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='flight.airline', verbose_name='پرواز')),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
                'db_table': 'flight',
            },
        ),
        migrations.CreateModel(
            name='FlightAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='اخرین بروزرسانی')),
                ('atribute_value', models.CharField(max_length=100, verbose_name='مقدار ويژگی')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='flight.flightattribute')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_attribute_values', to='flight.flight')),
            ],
            options={
                'verbose_name': 'FlightAttributeValue',
                'verbose_name_plural': 'FlightAttributeValues',
                'db_table': 'flight_attribute_value',
            },
        ),
    ]
