# Generated by Django 5.0 on 2023-12-19 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirLineAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=50, verbose_name='ويژگی')),
                ('value', models.CharField(max_length=50, verbose_name='مقدار')),
            ],
            options={
                'verbose_name': 'airline attribute',
                'verbose_name_plural': 'airline attributes',
                'db_table': 'airline attribute',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_price', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='قیمت پایه')),
                ('taxes_and_duties', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='مالیات و عوارض')),
                ('taxes_and_services', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='مالیات و خدمات')),
                ('value_added_tax', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='مالیات بر ارزش افزوده')),
                ('discount', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='تخفیف')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
                'db_table': 'price',
            },
        ),
        migrations.CreateModel(
            name='AirLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.CharField(max_length=64, verbose_name='نام شرکت هواپیما')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('airport_type', models.CharField(max_length=50, verbose_name='نوع هواپیما')),
                ('allowed_cargo', models.PositiveSmallIntegerField(verbose_name='بار مجاز')),
                ('airport_cabin', models.CharField(max_length=50, verbose_name='کابین')),
                ('airport_class', models.CharField(max_length=50, verbose_name='کلاس نرخی')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='airlines_price', to='flight.price')),
            ],
            options={
                'verbose_name': 'AirLine',
                'verbose_name_plural': 'AirLines',
                'db_table': 'airline',
            },
        ),
    ]
