# Generated by Django 5.0 on 2023-12-19 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='airline_attribute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='airlines', to='flight.airlineattribute'),
            preserve_default=False,
        ),
    ]
