# Generated by Django 5.0 on 2023-12-20 12:01

import django.db.models.deletion
import flight.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_number',
            field=flight.fields.CombindField(default=0, max_length=10, verbose_name='شماره پرواز'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='aairline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='flight.airline', verbose_name='شرکت هواپیمایی'),
        ),
    ]
