# Generated by Django 5.0 on 2023-12-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='airline',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='اخرین بروزرسانی'),
        ),
        migrations.AddField(
            model_name='flight',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='flight',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='اخرین بروزرسانی'),
        ),
        migrations.AddField(
            model_name='flightattribute',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='flightattribute',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='اخرین بروزرسانی'),
        ),
        migrations.AddField(
            model_name='flightattributevalue',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='flightattributevalue',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='اخرین بروزرسانی'),
        ),
        migrations.AddField(
            model_name='price',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='price',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='اخرین بروزرسانی'),
        ),
    ]
