# Generated by Django 5.0 on 2023-12-20 12:13

import flight.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_flight_flight_number_alter_flight_aairline'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightattributevalue',
            name='is_public_value',
            field=models.BooleanField(default=True, verbose_name='وضعیت انتشار مقدار'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=flight.fields.CombindField(help_text='3 characters is air and 7 next characters is digits', max_length=10, verbose_name='شماره پرواز'),
        ),
    ]
