# Generated by Django 5.0 on 2023-12-19 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_airline_airline_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='airline_attribute',
        ),
        migrations.AddField(
            model_name='airlineattribute',
            name='airline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='airline_attribute', to='flight.airline'),
            preserve_default=False,
        ),
    ]
